### ISSUE TITLE
How to test for project or directory?

### ISSUE THREAD

**Issue by msageryd** [emeraldwalk/vscode-runonsave#13]
What a great plugin! This might help me migrate from Atom to VSCode.

How can I test for files in a certain directory? Or even better, files in a certain project.

I want to run an rsync command when files in one of my directories or its subdirectories are saved. I suppose I can do this with the match parameter, but I can't figure out how.

**Comment by bmingles** [comment]
@michaelswe For testing files in a project, you can configure the extension in your workspace settings instead of your user settings. Any settings set at the workspace level should only apply to that workspace.

For targetting folders, you could probably use the `match` parameter as you mentioned. It is just a regex string. Note that the path separator is OS specific (Windows = \\, Mac = /, Linux = /). Since you will be setting this in a JSON value, backslashes will need to be double escaped (\\ becomes \\\\)

eg. in Windows

`c:\some\path\*.txt`

could be targetted using the Regex

`\\some\\path\\[^\\]+\.txt$`

Which would need additional escaping once put in JSON

`{
    "match": "\\\\some\\\\path\\\\[^\\\\]+\\.txt$"
}`

**Comment by michaelswe** [comment]
Brilliant!
I hadn't even noticed that there were workspace specific settings. VSCode seems better for each day.

And, I see now why my match attempts failed. I used far to few backslashes in my regexp ;)
