### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by guoliang** [emeraldwalk/vscode-runonsave#20]
I have the following configuration set

	"emeraldwalk.runonsave": {
		"shell": "/usr/local/bin/bash",
		"commands": [
			{"match": ".*", "cmd": "echo ${file}"}

		]
	}

And I expect it to output something in the internal console, but nothing happens. Where is the output going? I'm using VSCode on a Mac

**Comment by promethyttrium** [comment]
Me either. And it looks like there hasn't been any updates in a long time....

**Comment by bmingles** [comment]
@guoliang @promethyttrium Sorry for the late reply on this. The extension has its own output panel. If you click on the "Output" tab and then select "Run On Save" in the dropdown, you should see the output. Please let me know if you are not seeing this there.

**Comment by general03** [comment]
I have the same issue, in my "Run and save" console I have only `Run On Save enabled.`

**Comment by salientknight** [comment]
Same issue as general03 -- just using sample settings with simple modifications and I don't get any output 
`  "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.js$",
                "cmd": "echo 'I am a .js file ${file}.'"
            },
            {
                "match": "\\.scss$",
                "cmd": "echo 'I am an .scss file ${file}.'"
            },
            
        ]
    }`
![screen shot 2018-11-29 at 9 57 02 am](https://user-images.githubusercontent.com/40220684/49230285-4eba4980-f3bd-11e8-9c55-97e6b5afeb62.png)

**Comment by salientknight** [comment]
Had the same problem as general03 -- closing and reopening Code got things working

**Comment by AllDayAlone** [comment]
Please add this to doc

> @guoliang @promethyttrium Sorry for the late reply on this. The extension has its own output panel. If you click on the "Output" tab and then select "Run On Save" in the dropdown, you should see the output. Please let me know if you are not seeing this there.

**Comment by Spud-maker** [comment]
I am just starting with VSCode...
I've got exactly the code above inserted in User > settings.json.  I've got the Output tab selected, and "Run on Save" in DD.
It appears to run but does not show the echo of filename. only "Running on save commands..." appears in output when a file is saved.

Am I missing something or is this just borked?  Others seem to have this "working" but I can't get a basic hello world to work using it.   I will look at allegedly working "Save on Run" version next.

Only looking into this because no armv6l support for Remote-development.  I have a target system of Raspberry Pi that doesn't use arm7 or arm8 (too power hungry!)

Any help or greater understanding appreciated.  Any solution for armv6l support for Remote-dev also greatly appreciated...

**Comment by PWrzesinski** [comment]
Commenting as I came here via Google looking for an answer to the extension not running commands at all. In my case I stored the configuration in *.code-workspace file but then opened the project in vscode as folder, not from the workspace file, so the configuration was not loaded. Maybe it will help someone.
