### ISSUE TITLE
Run both user AND workspace settings

### ISSUE THREAD

**Issue by WORMSS** [emeraldwalk/vscode-runonsave#76]
I guess I said how good this extension is too much to my co-workers and they have added it to the workspace, and added settings into `.vscode/settings.json`.

The problem I have, is I have ADDITIONAL settings that are my personal commands in my 'user' settings.
But the workspace settings are taking priority and it now acts like my personal settings dont exist, and so there are so many things just not working anymore.

Is there a way to run both?

**Comment by bmingles** [comment]
@WORMSS As far as I know specific keys set in workspace settings will always override user settings. Since all commands are in a single “commands” array setting, workspace settings win. It should use user settings for other keys you haven’t set in the workspace, but I don’t think there’s a way to merge an array from both configs. It’s possible there is some way to query the user settings directly, although I have not seen this yet. Even if this is possible, I’m not sure how the extension could determine how to merge commands since there is sequencing involved. As far as I know this is consistent with how VS code settings, work, across-the-board, and not specific to the extension.

Something that might work is if you configure settings for specific languages. It’s possible user settings targeting a specific language may take precedence over workspace settings targeting all languages. I haven’t actually tested this, and it may not work for your specific scenario, but it might be worth experimenting with.

The other option that comes to mind is to open the workspace in a way that the workspace settings don’t apply. For example if it’s configured to be opened as a folder, you could add the folder to a workspace file, and the folder settings may not actually be applied. This also would be dependent on your specific scenario.

**Comment by WORMSS** [comment]
I just delete the workspace settings.. but never commit it.. I keep the removal as a stash and just keep applying it, without removing it from the stack.

Worked fine so far for 1½ years..

**Comment by bmingles** [comment]
Ah yes I had to do similar before. I’ve also used a pre-commit hook that automatically removes certain files from any commit. You don’t even have to stash. Sometimes it bites me when I want to actually make a change to the file and I forget about the hook. 😀

**Comment by WORMSS** [comment]
I rebase/switch branches/merge commits, a lot, so I need a clean tree quite often..

**Comment by bmingles** [comment]
Going to close as I don’t think there’s anything actionable.
