### ISSUE TITLE
how to match exclude .vscode folder

### ISSUE THREAD

**Issue by ruanimal** [emeraldwalk/vscode-runonsave#80]
I wan't to exclude vscode config folder from regex match, but not work.

I have try these 
- `"match": "^(?!\\.vscode).*$"`
- `"match": "^[^.].*$"`

config
```
{
    "emeraldwalk.runonsave": {
        "autoClearConsole": true,
        "commands": [
            {
                "match": ".*",
                "isAsync": true,
                "cmd": "rsync -av --exclude=target/ \"${workspaceFolder}/\"  /somewhere"
            },
        ]
    }
}
```

**Comment by iwconfig** [comment]
`"notMatch": ".vscode/*"`

**Comment by bmingles** [comment]
@ruanimal I think you were close but starting the regex with `^` is usually not going to be what you want since the match is against the full path.

I think this should do what you want:
```json
{
    "emeraldwalk.runonsave": {
        "autoClearConsole": true,
        "commands": [
            {
                "match": ".*",
                "notMatch": ".vscode/.*$",
                "isAsync": true,
                "cmd": "rsync -av --exclude=target/ \"${workspaceFolder}/\"  /somewhere"
            },
        ]
    }
}
```

The `notMatch` option was not previously documented (sorry about that). It has been added to documentation in https://github.com/emeraldwalk/vscode-runonsave/pull/100
