### ISSUE TITLE
Negotiation in match

### ISSUE THREAD

**Issue by ripetti** [emeraldwalk/vscode-runonsave#86]
Hi,

I've got a file named parity.js
I generate a parity number into this file before every save by _runonsave_ extension.

I would like to config _runonsave_ to run in case of saving every .js and .css and .html. The only exception that if I change parity.js file itself. (in some situation I have to write it manually)
If parity.js has been changed then _runonsave_ extension shouldn't run.
But I cannot create a valid match string to achieve this. Changing of parity.js always triggers _runonsave_ indeed.

My config is:

```
"emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "^(?!parity\.js)(.+\.js|.+\.css|.+\.html)$",
                "isAsync": false, 
                "cmd": "echo export const parity = %RANDOM%; > parity.js"
            },
        ]
    },
```

What match string do I need to feel the wonderful fragrance of success?
Thx.

**Comment by bmingles** [comment]
@ripetti An important thing to note is that you won't want to use the leading `^` since the match is run against the full path of the file. The only cases where you'd want this would be if your regex actually included an absolute path to match.

I think this regex should work for what you want for your scenario:

```javascript
(\b(?!parity\b)\w+\.js)|.+\.(html|css)$
```

Here's what it looks like on `regex101.com`
<img width="580" alt="image" src="https://github.com/user-attachments/assets/de41f2f8-7e01-4595-bd58-8eb4f2198caa">

And to use in the `vscode` extension, you'll need to escape the `\` characters by doubling them:

```json
"match": "(\\b(?!parity\\b)\\w+\\.js)|.+\\.(html|css)$",
```

**Comment by bmingles** [comment]
@ripetti actually a cleaner config would be to use `notMatch` which I just realized is undocumented.

```json
{
    "match": "\\.(html|css|js)$",
    "notMatch": "parity\\.js$",
    "isAsync": false,
    "cmd": "echo export const parity = %RANDOM%; > parity.js"
}
```

I've created [Document notMatch #99](https://github.com/emeraldwalk/vscode-runonsave/issues/99) to address documenting the `notMatch`.
