### ISSUE TITLE
Handling Paths with Spaces

### ISSUE THREAD

**Issue by karutt** [emeraldwalk/vscode-runonsave#87]
I've identified an issue where file paths containing spaces do not get correctly retrieved using placeholders like $FILE within this VSCode plugin. For instance, when using this plugin with files on iCloud Drive, the expected path to be obtained through $FILE should be `/Users/username/Library/Mobile Documents/com~apple~CloudDocs/Documents/test.md`. However, it instead results in `/Users/username/Library/Mobile`, truncating the path at the space within "Mobile Documents". This indicates that the space in the directory name is causing the issue.

To address these problems, I suggest modifying the extension.ts file as follows:
```js
cmdStr = cmdStr.replace(/\${file}/g, `'${document.fileName}'`);
// DEPRECATED: workspaceFolder is more in line with vscode variables,
// but leaving old version in place for any users already using it.
cmdStr = cmdStr.replace(/\${workspaceRoot}/g, `'${workspaceFolderPath}'`);
cmdStr = cmdStr.replace(/\${workspaceFolder}/g, `'${workspaceFolderPath}'`);
cmdStr = cmdStr.replace(/\${fileBasename}/g, `'${path.basename(document.fileName)}'`);
cmdStr = cmdStr.replace(/\${fileDirname}/g, `'${path.dirname(document.fileName)}'`);
cmdStr = cmdStr.replace(/\${fileExtname}/g, `'${extName}'`);
cmdStr = cmdStr.replace(/\${fileBasenameNoExt}/g, `'${path.basename(document.fileName, extName)}'`);
cmdStr = cmdStr.replace(/\${relativeFile}/g, `'${relativeFile}'`);
cmdStr = cmdStr.replace(/\${cwd}/g, `'${process.cwd()}'`);

// replace environment variables ${env.Name}
cmdStr = cmdStr.replace(/\${env\.([^}]+)}/g, (sub: string, envName: string) => {
    return `'${process.env[envName]}'`;
});

```
In the original code:

```typescript
cmdStr = cmdStr.replace(/\${file}/g, '${document.fileName}');
```

the intention was to dynamically replace the placeholder `${file}` with the actual file path stored in `document.fileName`. However, this approach fails to handle paths containing spaces correctly. When a path includes spaces, such as in directory names (`Mobile Documents` in our iCloud Drive example), the command constructed does not recognize the entire path as a single entity, leading to an incomplete path being processed.

To resolve this issue, the new code modification introduces single quotes around the `${document.fileName}`, as shown below:

```typescript
cmdStr = cmdStr.replace(/\${file}/g, `'${document.fileName}'`);
```

**Comment by benblank** [comment]
I don't believe this would be a good change; I think the quoting of paths should be handled by the author of the commands, not directly by the extension. If it's handled by the author, then a decision can be made whether or not the path is being used in a context where spaces are relevant, but if it's something the extension *just does*, it doesn't have any way of knowing whether it's a good idea or not.

For example, a command like `cp ${file} /backups` can always be changed to `cp "${file}" /backups` if you need to handle paths with spaces (or just as habit, as there are several characters which are allowable in paths but have special meaning to the shell). Alternatively, imagine a path is being used in a context where the single quote character has an undesirable meaning ­— for example, generating code for use in a language like C, where single quotes denote single characters rather than strings. If the path is being quoted by the extension, then the user authoring a command may not be able to work around the issue easily, if at all.

``` c
/* Current behavior: works just fine; the second arg is a cstring. */
execlp("some-fancy-command", "${file}");

/* Extension adds quotes: breaks, because single quotes make a char, not a cstring. */
execlp("some-fancy-command", ${file});

/* Extension adds quotes: breaks, because the single quotes get passed directly
   to some-fancy-command (without being interpreted by a shell) and aren't present
   in the actual path. */
execlp("some-fancy-command", "${file}");

/* Extension adds quotes: works, but needs a lot of extra effort to undo the quoting. */
char *quotedPath = "${file}";
size_t quotedPathLength = strlen(quotedPath);
char *path = malloc(quotedPathLength - 1);
strncpy(path, quotedPath + 1, quotedPathLength - 2);
path[quotedPathLength - 1] = '\0';
execlp("some-fancy-command", path);
free(path);
```

I'm not going to claim that "use a shell command to generate C code" is a common use case, of course, but it's an example of what can go wrong if the extension starts editing commands before it executes them. Better to let the command author decide how to handle things, in my opinion.

**Comment by bmingles** [comment]
I tend to agree with @benblank on this one. Thanks for the suggestion.
